Updated fzf scripts

diff --git a/home/features/fzf/scripts/fv b/home/features/fzf/scripts/fv
--- a/home/features/fzf/scripts/fv
+++ b/home/features/fzf/scripts/fv
@@ -1,49 +1,36 @@
 #!/usr/bin/env bash
 
-
-
 usage() {
   LESS=-FEXR less <<'HELP'
 fv [OPTIONS] [SEARCH]
-fuzzy file filtering and command executing
+Fuzzy file filtering and command executing
 
-a) allfiles=1 ;;
-c) cmd="$OPTARG" ;;
-d) dtach=1 ;;
-o) loop=1 ;;
-s) small=1 ;;
+Options:
+  -a          Search all directories and hidden files
+  -c CMD      Command to execute [defaults to vim]
+  -d          Run in background (detached)
+  -h          Show this help
+  -l          Additional search program options
+  -o          Run continuously
+  -s          Use a smaller window
 
--a    search all dirs and hidden files (possibly quirky)
--c    command to execute [defaults to vim]
--d    run in background (for ie non-terminal programs)
--h    show this help
--l    additional arguments to pass to filtering program
--o    run continuously
--s    run in a smaller window
+Environment:
+  FV_CMD       Override the editor
+  FV_SEARCH    Override the search tool (rg/ag/ack/grep)
 HELP
 }
 
-declare cmd=''
-declare cmdopts=()
-declare search_str=''
-declare search_cmd=''
-declare search_opts=()
-declare allfiles=''
-declare loop
-declare small
+# -------- Colors --------
 declare -A colors
-colors[red]=$(tput setaf 1)
-colors[green]=$(tput setaf 2)
-colors[blue]=$(tput setaf 4)
+colors[red]=$(tput setaf 1)$(tput bold)
+colors[green]=$(tput setaf 2)$(tput bold)
+colors[blue]=$(tput setaf 4)$(tput bold)
 colors[reset]=$(tput sgr0)
 
 color() {
-  local c
-  c="$1"
+  local c="$1"
   shift
-  printf '%s' "${colors[$c]}"
-  printf '%s\n' "$@"
-  printf '%s' "${colors[reset]}"
+  printf '%s%s%s\n' "${colors[$c]}" "$*" "${colors[reset]}"
 }
 
 err() {
@@ -55,17 +42,15 @@ die() {
   exit 1
 }
 
+# -------- Helpers --------
 has() {
-  local o c verbose
-  verbose=0
+  local o verbose=0 c
   while getopts 'v' o; do
-    case "$o" in
-      v) v=1 ;;
-    esac
+    case "$o" in v) verbose=1 ;; esac
   done
   shift "$((OPTIND-1))"
-  for c; do c="${c%% *}"
-    if ! command -v "$c" &> /dev/null; then
+  for c; do
+    if ! command -v "${c%% *}" &> /dev/null; then
       (( verbose > 0 )) && err "$c not found"
       return 1
     fi
@@ -73,8 +58,7 @@ has() {
 }
 
 select_from() {
-  local o c cmd OPTARG OPTIND
-  cmd='command -v'
+  local o cmd='command -v' c
   while getopts 'c:' o; do
     case "$o" in
       c) cmd="$OPTARG" ;;
@@ -90,6 +74,19 @@ select_from() {
   return 1
 }
 
+get_preview_command() {
+  select_from 'bat --color=always --style=header' \
+              'highlight -q --force -O ansi' \
+              'cat'
+}
+
+# -------- Vars --------
+declare cmd='' cmdopts=()
+declare search_cmd='' search_str=''
+declare search_opts=()
+declare allfiles='' loop='' small='' dtach=''
+
+# -------- Arg Parse --------
 while getopts 'ac:dhlos' opt; do
   case "$opt" in
     a) allfiles=1 ;;
@@ -103,26 +100,27 @@ while getopts 'ac:dhlos' opt; do
 done
 shift "$((OPTIND-1))"
 
-has -v 'fzf' || die
+# -------- Prechecks --------
+has -v 'fzf' || die "fzf is required but not found"
 
+# Editor
 if [[ -v FV_CMD ]]; then
   cmd="$FV_CMD"
 elif [[ -z "$cmd" ]]; then
-  cmd=$(select_from 'v' 'vim')
+  cmd=$(select_from 'nvim' 'vim' 'vi')
 fi
+[[ -z "$cmd" ]] && die "No suitable editor found."
 
-
+# Search Tool
 if [[ -v FV_SEARCH ]]; then
   search_cmd="$FV_SEARCH"
 else
-  search_cmd=$(select_from 'ag' 'ack' 'grep')
+  search_cmd=$(select_from 'rg' 'ag' 'ack' 'grep')
 fi
+[[ -z "$search_cmd" ]] && die "No search tool found (install rg/ag/ack/grep)"
+[[ "$search_cmd" == "grep" ]] && err "Warning: grep is slow. Consider installing rg or ag." && sleep .75
 
-if [[ "$search_cmd"  == 'grep' ]]; then
-  err 'grep is slow, you should strongly consider installing ag or ack'
-  sleep .75
-fi
-
+# Input
 if [[ -n "$1" ]]; then
   if [[ -e "$1" ]]; then
     search_opts+=( "$1" )
@@ -132,37 +130,26 @@ if [[ -n "$1" ]]; then
   shift
 fi
 
+# -------- Search Options --------
 case "$search_cmd" in
   'rg')
     search_opts+=( '--color=always' )
-    if [[ -n "$allfiles" ]]; then
-      search_opts+=( '--hidden' '--no-ignore' )
-    fi
-    if [[ -z "$search_str" ]]; then
-      search_opts+=( '-l' )
-    fi
-    if [[ -z "$allfiles" ]]; then
-      search_opts+=( '--glob=!{bower_components,node_modules,jspm_packages,.cvs,.git,.hg,.svn}' )
-    fi ;;
+    [[ -n "$allfiles" ]] && search_opts+=( '--hidden' '--no-ignore' )
+    [[ -z "$search_str" ]] && search_opts+=( '-l' )
+    [[ -z "$allfiles" ]] && search_opts+=( '--glob=!{bower_components,node_modules,jspm_packages,.cvs,.git,.hg,.svn}' )
+    ;;
   'ag')
     search_opts+=( '--color' )
-    if [[ -n "$allfiles" ]]; then
-      search_opts+=( '-u' '--hidden' )
-    fi
-    if [[ "$search_str" == '' ]]; then
-      search_opts+=( '-l' )
-    fi ;;
+    [[ -n "$allfiles" ]] && search_opts+=( '-u' '--hidden' )
+    [[ -z "$search_str" ]] && search_opts+=( '-l' )
+    ;;
   'ack')
-    if [[ "$search_str" == '' ]]; then
-      if [[ -z "$allfiles" ]]; then
-        search_opts+=( '-f' )
-      else
-        search_opts+=( '-g' '^[^\.]' )
-      fi
+    if [[ -z "$search_str" ]]; then
+      [[ -z "$allfiles" ]] && search_opts+=( '-f' ) || search_opts+=( '-g' '^[^\.]' )
     else
       search_opts+=( '-l' )
-    #   search_opts+=( '--match' )
-    fi ;;
+    fi
+    ;;
   'grep')
     search_opts+=( '-r' '-I' )
     if [[ -z "$allfiles" ]]; then
@@ -171,39 +158,28 @@ case "$search_cmd" in
           search_opts+=( "--exclude-dir=$line" )
         done < ~/.ignore
       else
-        search_opts+=( '--exclude-dir=bower_components' )
-        search_opts+=( '--exclude-dir=node_modules' )
-        search_opts+=( '--exclude-dir=jspm_packages' )
-        search_opts+=( '--exclude-dir=.cvs' )
-        search_opts+=( '--exclude-dir=.git' )
-        search_opts+=( '--exclude-dir=.hg' )
-        search_opts+=( '--exclude-dir=.svn' )
+        search_opts+=( '--exclude-dir={bower_components,node_modules,jspm_packages,.cvs,.git,.hg,.svn}' )
       fi
     fi
-    if [[ -z "$search_str" ]]; then
-      search_opts+=( -F '' )
-    else
-      search_opts+=( -P )
-    fi ;;
+    [[ -z "$search_str" ]] && search_opts+=( -F '' ) || search_opts+=( -P )
+    ;;
 esac
 
-if [[ "$search_str" != '' ]]; then
-  search_opts+=( "$search_str" )
-fi
+[[ -n "$search_str" ]] && search_opts+=( "$search_str" )
 
+# -------- Main Execution --------
 main() {
-  local highlight
-  highlight=$(select_from  'bat --color=always --style=header' 'highlight -q --force -O ansi')
-  choices=$($search_cmd "${search_opts[@]}" 2> /dev/null |
-    fzf --ansi --multi --preview="[[ \$(file -ib {}) = *text* ]] && ${highlight} {}") || exit 1
+  local choices preview
+  preview=$(get_preview_command)
 
-  if [[ "$search_str" != '' ]]; then
-    if [[ $search_cmd == 'ag' ]]; then
-      choices=$(cut -d: -f1 <<< "$choices")
-    fi
-  fi
+  choices=$($search_cmd "${search_opts[@]}" 2> /dev/null |
+    fzf --ansi --multi --preview="[[ \$(file -ib {}) == text/* ]] && $preview {} || echo 'Binary file'" --preview-window=right:60%) || return 1
+
+  # Handle results
+  [[ "$search_str" != '' && "$search_cmd" == 'ag' ]] && choices=$(cut -d: -f1 <<< "$choices")
 
   mapfile -t choices <<< "$choices"
+  [[ ${#choices[@]} -eq 0 ]] && return 1
 
   if [[ $dtach ]]; then
     ($cmd "${cmdopts[@]}" "${choices[@]}" &> /dev/null &)
@@ -212,10 +188,9 @@ main() {
   fi
 }
 
+# -------- Loop Mode --------
 if [[ -n "$loop" ]]; then
-  while main; do
-    true
-  done
+  while main; do true; done
 else
   main
 fi
